* Containers
** Building Images
To build images use the followin =-t= flag to pass a "tag" to the image. Use =-f= to signify the specific container.
#+begin_src bash
$ podman build -t imageName .
#+end_src
** Naming images
*** distro-noun/verb-cont
** Malware Analysis
*** DONE Fedora
#+begin_src containerfile :tangle ~/Projects/infosec_containers/malware_analysis/fedora/Containerfile
FROM fedora-minimal:42

RUN dnf install -y \
  gdb \
  strace \
  ltrace \
  binwalk \
  yara \
  p7zip \
  emacs-nox

RUN mkdir /home/app
WORKDIR /home/app
#+end_src
*** TODO Bootc
#+begin_src containerfile
FROM quay.io/fedora/fedora-bootc:42 as base

RUN dnf install -y \
  ...
  ...
  ..

RUN
#+end_src
*** TODO Debian
#+begin_src containerfile
FROM debian:12

RUN apt-get install -y \
   gdb \
   strace \
   ltrace \
   binwalk \
   yara \
   p7zip \
   emacs-nox\

RUN
#+end_src
*** Nix
*** Tools
**** gdb
**** strace
**** ltrace
**** binwalk
**** yara
**** p7zip
**** emacs-nox
** Network Analysis
*** Tools
**** wireshark?
**** suricata
**** tshark?
**** tcpdump
**** fiddler?
**** nmap
*** Fedora
#+begin_src containerfile :tangle ~/Projects/infosec_containers/network_analysis/fedora/Containerfile
FROM fedora-minimal:42

RUN dnf install -y \
  tshark \
  tcpdump \
  nmap \
  emacs-nox

RUN mkdir /home/samples
WORKDIR /home/samples
#+end_src
** Log Analysis
** DONE Email Analysis
#+begin_src containerfile
FROM fedora-minimal:42

RUN dnf install -y \
  yara \
  p7zip \
  file \
  clamav \
  clamd \
  clamav-update \
  emacs-nox

RUN mkdir /home/samples
WORKDIR /home/samples
#+end_src
** DONE Minimized Email Analysis
CLOSED: [2025-08-25 Mon 14:45]
#+begin_src containerfile :tangle ~/Projects/infosec_containers/email_analysis/fedora/Containerfile
FROM fedora-minimal:42

RUN microdnf install -y \
  clamav \
  clamd \
  clamav-update \
  mg \
  --nodocs --setopt install_weak_deps=False \
  && microdnf clean all -y

RUN mkdir /home/samples
WORKDIR /home/samples
#+end_src
*** Using the "scratch" method does not work
** All Tools
** Using the Containers
*** ma-fedora
You run Emacs straight out of the container.
#+begin_src bash
podman run --rm -it --name malcont ma-fedora /usr/bin/emacs
#+end_src
* Toolbox
** Building Images
To build a toolbox image you use a very similar process as with a regular podman image container. The main difference being that you must use a special container image from the toolbox project. Without this specific image Fedora will recognize the container a normal podman container.

Another thing to keep in mind, is the easier integration with the host system. You may not need to load the container up with a lot of packages if the host system already has them installed.
** Image/Containers Life-cycle
Here's a breakdown of how you should manage the images and containers. Every so often you will add or remove a package or configuration. Doing so will require you to stop, remove, build, create, and enter a toolbox container.
#+begin_src sh
  - podman build --squash --tag localhost/sec-tools . #In the directory where the Containerfile exist use this build command to create the image
  - podman images  #List all Podman Images
  - podman stop sec-tools #Stop the 'sec-tools' container (not image)
  - podman rm sec-tools #Remove the 'sec-tools' image (can't run container without the image)
  - toolbox list #Check if correct podman container was stopped and correct image was removedness
  - toolbox create sec-tools --image localhost/sec-tools:latest #Use toolbox to create the container from the image you built earlier
  - toolbox enter sec-tools #Enter the toolbox container you just created
#+end_src

** Naming Images
*** distro-noun/verb
** All Tools
#+begin_src containerfile :tangle ~/Projects/infosec_containers/toolbox/Containerfile
# Start from the official Fedora Toolbox Image
FROM registry.fedoraproject.org/fedora-toolbox:42

# Add Microsoft Powershell Repo
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    curl -s https://packages.microsoft.com/config/rhel/9/prod.repo | tee /etc/yum.repos.d/microsoft.repo

# Install All Tools
RUN dnf --assumeyes install \
    nmap \
    telnet \
    wireshark-cli \
    powershell \
    nc \
    bind-utils \
    bat \
    navi \
    yara && \
    dnf clean all

RUN dnf clean all

# Ensure the image is recognized by Toolbx
LABEL com.github.containers.toolbox="true"
#+end_src
** Minimal Tools
