FROM fedora-minimal:42

RUN microdnf install -y \
  clamav \
  clamd \
  clamav-update \
  mg \
  --nodocs --setopt install_weak_deps=False \
  && microdnf clean all -y

RUN mkdir /home/samples
WORKDIR /home/samples
